import './helper/common.css'
import "./font.css"
import "./globals.css";

import BootstrapInit from './helper/BootstrapInit';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";



export const metadata = {
  title: "ERP ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
    
      <body suppressHydrationWarning={true}>
      <script strategy='beforeInteractive' src={`https://www.google.com/recaptcha/api.js?render=${process.env.NEXT_PUBLIC_RECAPTCHA_SITE_KEY}`}></script>
      <BootstrapInit/>

        {children}
     
        
      </body>
    </html>
  );
}
